# Generated by Django 4.2 on 2023-08-12 07:40

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(help_text='Enter your date of birth', null=True, validators=[core.validators.date_is_past], verbose_name='Date of birth'),
        ),
    ]
