# Generated by Django 4.2 on 2023-08-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userconfirmationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfirmationcode',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
