# Generated by Django 4.2 on 2023-08-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userconfirmationcode_is_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfirmationcode',
            old_name='token',
            new_name='confirmation_code',
        ),
    ]
