# Generated by Django 4.2 on 2023-08-23 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_token_userconfirmationcode_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmationcode',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
