# Generated by Django 4.2 on 2023-08-12 12:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter your Number phone', max_length=128, region=None, verbose_name='Number phone'),
        ),
    ]
