# Generated by Django 4.2 on 2023-08-23 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userconfirmationcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='Enter your name', max_length=53, validators=[django.core.validators.MinLengthValidator(limit_value=1)], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='Enter your surname', max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=1)], verbose_name='Surname'),
        ),
    ]
