version: '3.3'
services:
  db:
    image: postgres:13.0-alpine 
    volumes:
      - db_storage:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  backend:
    image: pictura/marketgraphicimages:latest
    restart: always
    links:
      - db
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ./.env


volumes:
  db_storage:
  static_value:
  media_value:
