# Generated by Django 4.2 on 2023-08-30 07:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Любимое изображение',
                'verbose_name_plural': 'Любимые изображения',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается текущая дата и время', verbose_name='Дата создания')),
                ('name', models.CharField(help_text='Введите название', max_length=200, unique=True, verbose_name='Название')),
                ('image', models.ImageField(help_text='Добавьте изображение', unique=True, upload_to='Images/', verbose_name='Картинка')),
                ('license', models.CharField(choices=[('Платно', 'Платно'), ('Бесплатно', 'Бесплатно')], max_length=15)),
                ('price', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Цена изображения')),
                ('format', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TagImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(help_text='Выберите изображения', on_delete=django.db.models.deletion.CASCADE, to='images.image', verbose_name='Изображение')),
                ('tag', models.ForeignKey(help_text='Выберите из списка тег', on_delete=django.db.models.deletion.DO_NOTHING, to='tags.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(help_text='Выберите изображения', on_delete=django.db.models.deletion.CASCADE, to='images.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Купленное изображение',
                'verbose_name_plural': 'Купленные изображения',
            },
        ),
    ]
