# Generated by Django 4.2 on 2023-08-24 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Автоматически устанавливается текущая дата и время', verbose_name='Дата создания')),
                ('name', models.CharField(help_text='Введите название', max_length=200, unique=True, verbose_name='Название')),
                ('image', models.ImageField(help_text='Добавьте изображение', unique=True, upload_to='Images/', verbose_name='Картинка')),
                ('license', models.CharField(choices=[('Платно', 'Платно'), ('Бесплатно', 'Бесплатно')], max_length=15)),
                ('tip', models.CharField(choices=[('jpeg', 'jpeg'), ('png', 'png'), ('svg', 'svg'), ('gif', 'gif'), ('psd', 'psd')], max_length=10)),
                ('author', models.ForeignKey(help_text='Автор изображения', on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TagImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(help_text='Выберите изображения', on_delete=django.db.models.deletion.CASCADE, to='images.image', verbose_name='Изображение')),
                ('tag', models.ForeignKey(help_text='Выберите из списка тег', on_delete=django.db.models.deletion.DO_NOTHING, to='tags.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(help_text='Выберите изображения', on_delete=django.db.models.deletion.CASCADE, to='images.image', verbose_name='Изображение')),
                ('user', models.ForeignKey(help_text='Выберите из списка пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Купленное изображение',
                'verbose_name_plural': 'Купленные изображения',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(help_text='Выберите теги', through='images.TagImage', to='tags.tag', verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='FavoriteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(help_text='Выберите изображения', on_delete=django.db.models.deletion.CASCADE, to='images.image', verbose_name='Изображение')),
                ('user', models.ForeignKey(help_text='Выберите из списка пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Любимое изображение',
                'verbose_name_plural': 'Любимые изображения',
            },
        ),
        migrations.AddConstraint(
            model_name='tagimage',
            constraint=models.UniqueConstraint(fields=('image', 'tag'), name='unique_image_tag'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcartimage',
            constraint=models.UniqueConstraint(fields=('image', 'user'), name='unique_shopping_cart'),
        ),
        migrations.AddConstraint(
            model_name='favoriteimage',
            constraint=models.UniqueConstraint(fields=('image', 'user'), name='unique_favorite'),
        ),
    ]
