# Generated by Django 4.2 on 2023-08-30 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartimage',
            name='user',
            field=models.ForeignKey(help_text='Выберите из списка пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='image',
            name='author',
            field=models.ForeignKey(help_text='Автор изображения', on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(help_text='Выберите теги', through='images.TagImage', to='tags.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='favoriteimage',
            name='image',
            field=models.ForeignKey(help_text='Выберите изображения', on_delete=django.db.models.deletion.CASCADE, to='images.image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='favoriteimage',
            name='user',
            field=models.ForeignKey(help_text='Выберите из списка пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='tagimage',
            constraint=models.UniqueConstraint(fields=('image', 'tag'), name='unique_image_tag'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcartimage',
            constraint=models.UniqueConstraint(fields=('image', 'user'), name='unique_shopping_cart'),
        ),
        migrations.AddConstraint(
            model_name='favoriteimage',
            constraint=models.UniqueConstraint(fields=('image', 'user'), name='unique_favorite'),
        ),
    ]
