# Generated by Django 4.2 on 2023-08-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tip',
        ),
        migrations.AddField(
            model_name='image',
            name='format',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
